#!/usr/bin/env python
# encoding: utf-8
# a1batross, 2019
import os

def options(opt):
	# opt.load('java')
	print('opt android')
	opt.load('android')

	return

def configure(conf):
	conf.env.D8_DEBUG = conf.options.BUILD_TYPE != 'release'
	conf.load('android')

from waflib import TaskGen, Task, Build, Logs

def build(bld):
	tsk = bld(features = 'android javac',
		srcdir = 'src',
		compat = '1.6',
		name = 'storagehelper',
		keystore = bld.path.parent.find_node('debug.keystore'),
		debug = bld.env.D8_DEBUG,
		jni = [bld.path.parent.find_node('arm64-v8a/libfdhelper.so')],
		target_api = 29)
	tsk.env.append_unique('JAVACFLAGS', ['-target', '1.6'])
	tsk.post()

